### PR TITLE
Removed white spaces, new lines from cert key

### PR DESCRIPTION
**Pull request by GarryOne**
I was getting wrong cert string cause of the new lines and whitespaces. I've added a regex to remove them.
```
"cert":"\nMIIGNzCCBR+gAwIBAgIRAIgwRqGmpAjEdu+QhhQH4Z8wDQYJKoZIhvcNAQELBQAwbTESMBAGCgmS\nJomT8ixkARkWAmV1MRUwEwYKCZImiZPyLGQBGRYFdW5pb24xFDASBgoJkiaJk/IsZAEZFgRwYXJs\nMRIwEAYKCZImiZPyLGQBGRYCZXAxFjAUBgNVBAMTDUVQU2lnbiBTU0wgQ0EwHhcNMTgwOTI3MTMw\nODMzWhcNMjAwOTI3MTMwODM0WjCBnTESMBAGCgmSJomT8ixkARkWAmV1MRUwEwYKCZImiZPyLGQB\nGRYFdW5pb24xFDASBgoJkiaJk/IsZAEZFgRwYXJsMRIwEAYKCZImiZPyLGQBGRYCZXAxGzAZBgNV\nBAsTEkRHIElURUMvT1BFUkFUSU9OUzEpMCcGA1UEAxMgV2ViU1NPIEZlZGVyYXRpb24gcHJlLXBy\nb2R1Y3Rpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCLrlA2nl5WQdqVxy3khLAD\n67Wg1cyHPojXmdkn406m+pdPHCdE8HArJWKFzWozPpHaTfMg705tP9/Xar3PY5oOhK0dF40NTvG1\nACcZrNGRDZ+5Et5GxEb2h/CFQTs9nZtNszkh9EpmAXEcZ+sD9J9FDVmFMgHnvcQDe08mm7PwxF2d\nN87Hx5ljF3Ek/4D9Tv6NEF5BNYKnG7CJSr9bVchJE5Z7YKEbofI71PKJhaoncbMRNHsFd17BJB0d\nI/5VDNPrVGi08PzW33W3hkc0JTB17g2EDW+NV2aPfw6tAezB7cJAKLuix4m/fBB1sagZu6h9+4je\nxUL7+7U7iSuk0wgPAgMBAAGjggKfMIICmzATBgNVHSUEDDAKBggrBgEFBQcDATAOBgNVHQ8BAf8E\nBAMCA6gwEQYJYIZIAYb4QgEBBAQDAgZAMIGbBggrBgEFBQcBAQSBjjCBizBMBggrBgEFBQcwAoZA\naHR0cDovL2Vwc2lnbi5ldXJvcGFybC5ldXJvcGEuZXUvY2VydC9FUFNpZ24tQXBwbGljYXRpb25z\nLUNBLmNydDA7BggrBgEFBQcwAYYvaHR0cDovL29jc3AuZXBzaWduLmV1cm9wYXJsLmV1cm9wYS5l\ndS9vY3NwLnh1ZGEwgbAGA1UdIwSBqDCBpYAUTS+dUOqQWfE7Hptu7jWrO1zV7Z+heqR4MHYxEjAQ\nBgoJkiaJk/IsZAEZFgJldTEVMBMGCgmSJomT8ixkARkWBXVuaW9uMRQwEgYKCZImiZPyLGQBGRYE\ncGFybDESMBAGCgmSJomT8ixkARkWAmVwMR8wHQYDVQQDExZFUFNpZ24gQXBwbGljYXRpb25zIENB\nghEAogNpWL0SEKvW0pMQUKsJKDBFBgNVHSAEPjA8MDoGBFUdIAAwMjAwBggrBgEFBQcCARYkaHR0\ncDovL2Vwc2lnbi5ldXJvcGFybC5ldXJvcGEuZXUvQ1BTMH0GA1UdHwR2MHQwcqBwoG6GNmh0dHA6\nLy9lcHNpZ24uZXVyb3BhcmwuZXVyb3BhLmV1L2NybC9FUFNpZ24tU1NMLUNBLmNybIY0aHR0cDov\nL2Vwc2lnbi5lcC5wYXJsLnVuaW9uLmV1L2NybC9FUFNpZ24tU1NMLUNBLmNybDArBgNVHREEJDAi\ngiBXZWJTU08gRmVkZXJhdGlvbiBwcmUtcHJvZHVjdGlvbjAdBgNVHQ4EFgQUcEPmGNSthUQVEp1q\nTJQWb7d0y6UwDQYJKoZIhvcNAQELBQADggEBAMD5y0odP/JBFWsVg9sQUw23iWRAlq/VY710go+E\nRB3AH4HP1LWSyjnhJzWpfvSF4zQAaDvcqyc1/9ayS+Q4CldQ34gEmclZnZO0Vbvd+8NZUxgqW/Fy\njzPLkpi3lEpeNp7q+K7/+snU8EWSc+6P7Ei0Mjj1LncKzK1j/ROn4B0PbHZFdoGbvtbJ9pxWtx3H\n0jg3eLVj8RYDs9qVJ2HmJV7rWpVIHsYT+8+41TsePSoHBp5AP/tZlwUWZFzFimbgLh8TcRvIq/F2\n7cGlKQDYdQDOXU43qtO4IgWn1QV1bQthzojmNfTdYF1MrTFeIpCcGogbS90a6r3nFLkgFm+9r9U=\n                    "
````

### CODE REVIEW

**Comment by GarryOne** [comment]
@compwright , `trim()` seems to not be enough.

```
const str = `1 line
2 line`;

const withTrim = str.trim();
const withReplace = str.replace(/(\r\n|\n|\r|\s)/gm, '');

console.log('trim', JSON.stringify(withTrim));
console.log('replace', JSON.stringify(withReplace));
```

will output
```
"trim", "\"1 line\n2 line\""
"replace", "\"1line2line\""
```

**Comment by GarryOne** [comment]
@compwright I've added the unit tests.

**Comment by compwright** [comment]
Released as v2.3.0

**Comment by GarryOne** [comment]
@compwright thanks. You forgot to update the `CHANGELOG`.

**Pull request merged**
